# The programm computes the smallest R-subgroup containing a giving  set of vectors by computing the  Expanded Gaussion Elimination on the set of vectors ${v_1,...,v_k}$.

## It gives a basis of the R-subgroup containing a giving  set of vectors.

In [ ]:
import numpy as np

In [ ]:
GF9=GF(3**2, name='X', modulus=x^2 +x+2 )
elements=list(GF9)
reorder=[0,4,8,5,3,2,1,6,7]
R=[elements[i] for i in reorder]
R

[0, 2, 1, 2*X, 2*X + 2, 2*X + 1, X, X + 2, X + 1]

In [ ]:
Squares=[r**2 for r in R]
Squares=list(set(Squares))
def scmult (v,r):
    n=len(v)
    sq=np.isin(v,Squares)
    output=np.repeat(R[0],n)
    for i in range(n):
        if sq[i]==True:
            output[i]=v[i]*r
        else:
            output[i]=v[i]*r**3
    return output

In [ ]:
scmult([R[0],R[1],R[2],R[3],R[4],R[5],R[6], R[7],R[8]],R[8])

array([0, 2*X + 2, X + 1, 2*X + 1, 1, X, X + 2, 2*X, 2], dtype=object)

In [ ]:
LR=[[a] for a in R]

In [ ]:
Squares=[r**2 for r in R]
Squares=list(set(Squares))
inverses=[R[0]]
for i in range(1,len(R)):
    for j in range(1,len(R)):
        if scmult([R[i]],R[j])==1:
            inverses.append(R[j])
            break
def inv(r):
    if r==R[0]:
        return 'Divide by Zero Error'
    for i in range(len(R)):
        if r==R[i]:
            return inverses[i]

In [ ]:
def AGE(basis):
    alpha=R[3]
    beta=R[1]
    lambd=R[3]
    matrix=copy(basis)
    (rownumber,colnumber)=np.shape(matrix)
    rowcount=0
    earlyabort=False

    #normal GE
    for i in range(colnumber-1):

        trunccol=matrix[rowcount:,i]
        if np.any(trunccol)!=False:
            agestart=i+1
            ind=np.nonzero(trunccol)[0][0]       #index of first nonzero entry of truncated column
            dum=copy(matrix[rowcount,:])
            matrix[rowcount,:]=matrix[rowcount+ind,:]
            matrix[rowcount+ind,:]=dum           #swap rows
            matrix[rowcount,:]=scmult(matrix[rowcount,:],inv(matrix[rowcount,:][i]))

            for j in range(rownumber):
                if j!=rowcount:
                    matrix[j,:]=matrix[j,:]-scmult(matrix[rowcount,:],matrix[j,i])
            rowcount+=1

    matrix=matrix[~np.all(matrix == 0, axis=1)]    #delete zero rows
    (rownumber,colnumber)=np.shape(matrix)

    #start of expanded part
    for i in range(agestart,colnumber):
        col=matrix[:,i]
        indices=np.nonzero(col)[0]
        if len(indices)>=2: # if there is more than one non-zero element in extra row
            row1=matrix[indices[0],:]
            row1=scmult(matrix[indices[0],:],inv(row1[i]))
            row2=matrix[indices[1],:]
            row2=scmult(matrix[indices[1],:],inv(row2[i]))
            newrow=scmult((scmult(row1,alpha)+scmult(row2,beta)),lambd)-scmult(scmult(row1,alpha),lambd)-scmult(scmult(row2,beta),lambd)
            newrow=scmult(newrow,inv(newrow[i]))
            matrix=np.append(matrix,[newrow],axis=0)
            rownumber+=1
            for j in range(rownumber):

                if j!=rowcount:
                    matrix[j,:]=matrix[j,:]-scmult(matrix[-1,:],matrix[j,i])
            rowcount+=1
    return matrix

## Test 0 : Subspaces

In [ ]:
b=np.array([ [R[8],R[2],R[5]]
                ])
b

array([[X + 1, 1, 2*X + 1]], dtype=object)

In [ ]:
AGE(b)

array([[1, 2*X + 2, 2*X]], dtype=object)

In [ ]:
basis00=np.array([
                [R[2],R[2],R[1],R[8],R[2]],
                [R[0],R[0],R[0],R[4],R[2]],
                [R[2],R[2],R[2],R[7],R[2]]
                ])
basis00

array([[1, 1, 2, X + 1, 1],
       [0, 0, 0, 2*X + 2, 1],
       [1, 1, 1, X + 2, 1]], dtype=object)

In [ ]:
AGE(basis00)

array([[1, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=object)

In [ ]:
basis000=np.array([
                [R[3],R[8],R[0]],
                [R[0],R[5],R[7]]
                ])
basis000

array([[2*X, X + 1, 0],
       [0, 2*X + 1, X + 2]], dtype=object)

In [ ]:
AGE(basis000)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=object)

In [ ]:
basis0000=np.array([
                [R[3],R[8],R[0],R[5]],
                [R[1],R[5],R[7],R[0]]
                ])
basis0000

array([[2*X, X + 1, 0, 2*X + 1],
       [2, 2*X + 1, X + 2, 0]], dtype=object)

In [ ]:
AGE(basis0000)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=object)

In [ ]:
basis00000=np.array([
                [R[1],R[1],R[0],R[0],R[1]],
                [R[0],R[0],R[1],R[1],R[0]],
                [R[1],R[0],R[0],R[1],R[0]]
                ])
basis00000

array([[2, 2, 0, 0, 2],
       [0, 0, 2, 2, 0],
       [2, 0, 0, 2, 0]], dtype=object)

In [ ]:
AGE(basis00000)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]], dtype=object)

In [ ]:
basis0000000=np.array([
                [R[1],R[1],R[1],R[0],R[0]],
                [R[0],R[0],R[0],R[1],R[0]],
                [R[1],R[0],R[0],R[0],R[1]]
                ])
basis0000000

array([[2, 2, 2, 0, 0],
       [0, 0, 0, 2, 0],
       [2, 0, 0, 0, 2]], dtype=object)

In [ ]:
AGE(basis0000000)

array([[1, 0, 0, 0, 0],
       [0, 1, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=object)

In [ ]:
basis00000000=np.array([
                [R[1],R[2],R[3],R[0],R[0]],
                [R[0],R[0],R[0],R[1],R[0]],
                [R[1],R[0],R[0],R[0],R[1]]
                ])
basis00000000

array([[2, 1, 2*X, 0, 0],
       [0, 0, 0, 2, 0],
       [2, 0, 0, 0, 2]], dtype=object)

In [ ]:
AGE(basis00000000)

array([[1, 0, 0, 0, 0],
       [0, 1, 2*X, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=object)

In [ ]:
basis0000000000=np.array([
                [R[1],R[0],R[1]],
                [R[2],R[0],R[0]],
                [R[3],R[0],R[0]],
                [R[0],R[1],R[0]],
                [R[0],R[0],R[1]]
                ])
basis0000000000

array([[2, 0, 2],
       [1, 0, 0],
       [2*X, 0, 0],
       [0, 2, 0],
       [0, 0, 2]], dtype=object)

In [ ]:
AGE(basis0000000000)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, X],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=object)

In [ ]:
basis01=np.array([
                [R[1],R[1],R[0],R[0]],
                [R[1],R[0],R[1],R[0]],
                [R[1],R[0],R[0],R[1]]
                ])
basis01

array([[2, 2, 0, 0],
       [2, 0, 2, 0],
       [2, 0, 0, 2]], dtype=object)

In [ ]:
AGE(basis01)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=object)

In [ ]:
basis02=np.array([
                [R[3],R[1],R[1],R[0],R[0]],
                [R[2],R[4],R[1],R[1],R[0]],  [R[1],R[0],R[1],R[1],R[3]]

                ])
basis02

array([[2*X, 2, 2, 0, 0],
       [1, 2*X + 2, 2, 2, 0],
       [2, 0, 2, 2, 2*X]], dtype=object)

In [ ]:
AGE(basis02)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=object)

In [ ]:
basis03=np.array([
                [R[0],R[1],R[1],R[0],R[0]],
                [R[0],R[4],R[2],R[0],R[4]],  [R[1],R[4],R[1],R[0],R[3]]

                ])
basis03

array([[0, 2, 2, 0, 0],
       [0, 2*X + 2, 1, 0, 2*X + 2],
       [2, 2*X + 2, 2, 0, 2*X]], dtype=object)

In [ ]:
AGE(basis03)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1]], dtype=object)

In [ ]:
basistest=np.array([
                [R[1],R[3],R[1],R[8],R[1]],
                [R[3],R[6],R[3],R[0],R[3]],
                [R[1],R[4],R[1],R[0],R[2]]
                ])
basistest

array([[1, X, 1, 2*X + 2, 1],
       [X, 2*X, X, 0, X],
       [1, X + 1, 1, 0, 2]], dtype=object)